"""empty message

Revision ID: 7186ad9b9b92
Revises: b63ec9831ddd
Create Date: 2019-05-06 17:44:17.222103

"""

# revision identifiers, used by Alembic.
revision = '7186ad9b9b92'
down_revision = 'b63ec9831ddd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    ### end Alembic commands ###
