"""empty message

Revision ID: acf7168fbf13
Revises: None
Create Date: 2019-04-28 17:47:07.721141

"""

# revision identifiers, used by Alembic.
revision = 'acf7168fbf13'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat', sa.Column('rank', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat', 'rank')
    ### end Alembic commands ###
