"""empty message

Revision ID: e349e6e65eb1
Revises: acf7168fbf13
Create Date: 2019-04-29 22:00:40.312526

"""

# revision identifiers, used by Alembic.
revision = 'e349e6e65eb1'
down_revision = 'acf7168fbf13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('stat', schema=None) as batch_op:
    #     batch_op.drop_column('rank')
    ()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.INTEGER(), nullable=True))

    ### end Alembic commands ###
